swagger: "2.0"
info:
  description: "Magnet Api inpormation"
  version: "1.0.0"
  title: "Magnet Api"
host: "localhost:3000"
schemes:
  - "http"
paths:
  /api/v1/Users/signup:
    post:
      tags:
        - "Signup"
      summary: "use for signup"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User information"
          required: true
          schema:
            $ref: "#/definitions/signup"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Account created Successfully"

  /api/v1/Users/login:
    post:
      tags:
        - "login"
      summary: "use for login"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User information"
          required: true
          schema:
            $ref: "#/definitions/login"
      responses:
        "400":
          description: "email or password incorrect"
        "200":
          description: "logged In Successfully"

  /api/v1/Users:
    get:
      tags:
        - "Logout"
      summary: "use for logout"
      description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "operation successful"
definitions:
  signup:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"
      passwordConfirm:
        type: "string"
  login:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
